[package]
name = "encryption"
version = "0.1.0"
edition.workspace = true

[dependencies]
storage.workspace = true
ciphers.workspace = true
audit-log.workspace = true

prost.workspace = true

[build-dependencies]
prost-build.workspace = true
