[package]
name = "storage"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-trait.workspace = true

thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
